// MOVIE_LIST_REDUCER
export const INITIALIZE_STATE = 'INITIALIZE_STATE';
export const INITIALIZE_MOVIE_LIST = 'INITIALIZE_MOVIE_LIST';
// EDIT_MOVIE_REDUCER
export const INITIALIZE_EDIT_MOVIE = 'INITIALIZE_EDIT_MOVIE';
export const CLEAR_EDIT_MOVIE = 'CLEAR_EDIT_MOVIE';
export const CHANGE_EDIT_MOVIE_FILED = 'CHANGE_EDIT_MOVIE_FILED';
export const EDIT_MOVIE_OPEN_GENRE_SELECT = 'EDIT_MOVIE_OPEN_GENRE_SELECT';
export const EDIT_MOVIE_CLOSE_GENRE_SELECT = 'EDIT_MOVIE_CLOSE_GENRE_SELECT';
export const EDIT_MOVIE_CHECK_GENRE = 'EDIT_MOVIE_CHECK_GENRE';
export const SET_ERROR_TEXT_FOR_EDIT = 'SET_ERROR_TEXT_FOR_EDIT';
export const CLEAR_ERROR_TEXT_FOR_EDIT = 'CLEAR_ERROR_TEXT_FOR_EDIT';
export const CHANGE_MOVIE_FROM_LIST = 'CHANGE_MOVIE_FROM_LIST';
export const ADD_NEW_MOVIE_TO_LIST = 'ADD_NEW_MOVIE_TO_LIST';
export const DELETE_MOVIE_FROM_LIST = 'DELETE_MOVIE_FROM_LIST';

// ADD_MOVIE_REDUCER
export const CHANGE_NEW_MOVIE_FILED = 'CHANGE_NEW_MOVIE_FILED';
export const NEW_MOVIE_OPEN_GENRE_SELECT = 'NEW_MOVIE_OPEN_GENRE_SELECT';
export const NEW_MOVIE_CHECK_GENRE = 'NEW_MOVIE_CHECK_GENRE';

export const ADD_MOVIE_CLOSE_GENRE_SELECT = 'ADD_MOVIE_CLOSE_GENRE_SELECT';
export const CLEAR_ERROR_TEXT_FOR_ADD = 'CLEAR_ERROR_TEXT_FOR_ADD';
export const SET_ERROR_TEXT_FOR_ADD = 'SET_ERROR_TEXT_FOR_ADD';
export const CLEAR_NEW_MOVIE = 'CLEAR_NEW_MOVIE';