export const MOVIE_TITLE_ARRAY = [
    'Pulp Fiction',
    'The Manchurian Candidate',
    'Taxi Driver',
    'The Man Who Shot Liberty Valance',
    'Dunkirk',
    'Before Midnight',
    'The Godfather',
    'Faces Places',
    'A Separation',
    'Zero Dark Thirty',
    'Snow White and the Seven Dwarfs',
    'double',
    'I Am Not Your Negro',
    'The Social Network',
    'The Grapes of Wrath',
    'Toy Story',
    'Carol',
    'Beauty and the Beast',
    'Spirited Away'
];

export const GENRE_ARRAY = [
    'Action',
    'Comedy',
    'Family',
    'History',
    'Mystery',
    'Sci-Fi',
    'War',
    'Adventure',
    'Crime',
    'Fantasy',
    'Horror',
    'News',
    'Sport',
    'Western',
    'Animation',
    'Documentary',
    'Film-Noir',
    'Music',
    'Reality-TV',
    'Talk-Show',
    'Biography',
    'Drama',
    'Game-Show',
    'Musical',
    'Romance',
    'Thriller'
];
